import type { Route } from "next";
import Link from "next/link";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import type { getGeneralAcademicInventoryHealth } from "@/lib/general-academic/content-intelligence";
import { GENERAL_ACADEMIC_DIFFICULTIES, GENERAL_ACADEMIC_DOMAINS, GENERAL_ACADEMIC_DOMAIN_LABELS, GENERAL_ACADEMIC_ORIGINS, GENERAL_ACADEMIC_REVIEW_STATUSES } from "@/lib/general-academic/registries";

type Health = ReturnType<typeof getGeneralAcademicInventoryHealth>;
type Filters = { lifecycle?: string; domain?: string; difficulty?: string; origin?: string; issue?: string };
const inputClass = "h-10 min-w-0 rounded-md border border-workspace-border bg-surface-lowest px-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary";

function label(value: string) {
  return value.replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase());
}

export function GeneralAcademicQualityDashboard({ health, filters }: { health: Health; filters: Filters }) {
  const audits = health.audit.audits.filter((audit) => {
    const { pack } = audit.item;
    if (filters.lifecycle && pack.review.status !== filters.lifecycle) return false;
    if (filters.domain && pack.domain !== filters.domain) return false;
    if (filters.difficulty && pack.difficulty !== filters.difficulty) return false;
    if (filters.origin && pack.origin !== filters.origin) return false;
    if (filters.issue === "blocking" && !audit.blocking.length) return false;
    if (filters.issue === "warning" && !audit.warnings.length) return false;
    if (filters.issue === "similarity" && !audit.similarity.length) return false;
    return true;
  });
  return (
    <div className="space-y-6">
      <dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        {[["Blocking issues", health.counts.blocking], ["Warnings", health.counts.warnings], ["Similarity alerts", health.counts.duplicateAlerts], ["Coverage gaps", health.counts.missingCoverage]].map(([name, value]) => <div className="rounded-lg border border-workspace-border bg-surface-lowest p-4" key={name}><dt className="text-sm text-muted-foreground">{name}</dt><dd className="mt-1 text-2xl font-semibold">{value}</dd></div>)}
      </dl>
      {health.audit.answerDistributionWarning ? <p className="rounded-lg border border-warning/30 bg-warning-container p-4 text-sm"><strong>Answer-position signal:</strong> {health.audit.answerDistributionWarning}</p> : null}
      <Card><CardHeader><CardTitle>Audit filters</CardTitle><CardDescription>Deterministic findings aggregate the Phase 4 validator with Phase 8 inventory and similarity signals.</CardDescription></CardHeader><CardContent><form className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5" method="get"><label className="grid gap-1 text-sm font-semibold">Lifecycle<select className={inputClass} defaultValue={filters.lifecycle ?? ""} name="lifecycle"><option value="">All</option>{GENERAL_ACADEMIC_REVIEW_STATUSES.map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold">Domain<select className={inputClass} defaultValue={filters.domain ?? ""} name="domain"><option value="">All</option>{GENERAL_ACADEMIC_DOMAINS.map((value) => <option key={value} value={value}>{GENERAL_ACADEMIC_DOMAIN_LABELS[value]}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold">Difficulty<select className={inputClass} defaultValue={filters.difficulty ?? ""} name="difficulty"><option value="">All</option>{GENERAL_ACADEMIC_DIFFICULTIES.map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold">Origin<select className={inputClass} defaultValue={filters.origin ?? ""} name="origin"><option value="">All</option>{GENERAL_ACADEMIC_ORIGINS.map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold">Issue<select className={inputClass} defaultValue={filters.issue ?? ""} name="issue"><option value="">All</option><option value="blocking">Blocking</option><option value="warning">Warnings</option><option value="similarity">Similarity</option></select></label><div className="flex flex-wrap gap-2 xl:col-span-5"><Button type="submit">Apply filters</Button><Button asChild variant="outline"><Link href={"/admin/general-academic/quality" as Route}>Clear</Link></Button></div></form></CardContent></Card>

      <section aria-labelledby="audit-results" className="space-y-3"><div><h2 className="text-xl font-semibold" id="audit-results">Pack health</h2><p className="mt-1 text-sm text-muted-foreground">{audits.length} matching pack{audits.length === 1 ? "" : "s"}. Similarity is a review signal, not a plagiarism verdict.</p></div>{audits.map((audit) => <Card key={audit.item.id}><CardHeader><div className="flex flex-wrap items-center gap-2"><CardTitle>{audit.item.pack.title}</CardTitle><Badge variant="subtle">{label(audit.item.pack.review.status)}</Badge><Badge variant="subtle">{GENERAL_ACADEMIC_DOMAIN_LABELS[audit.item.pack.domain]}</Badge></div><CardDescription>{audit.item.pack.questions.length} questions · PrepDMAT {label(audit.item.pack.difficulty)} · {label(audit.item.pack.origin)}</CardDescription></CardHeader><CardContent className="space-y-4"><dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs uppercase text-muted-foreground">Validation</dt><dd className="font-semibold">{audit.blocking.length ? `${audit.blocking.length} blocking` : "Pass"}</dd></div><div><dt className="text-xs uppercase text-muted-foreground">Quality</dt><dd className="font-semibold">{audit.warnings.length} warnings</dd></div><div><dt className="text-xs uppercase text-muted-foreground">Similarity</dt><dd className="font-semibold">{audit.similarity.length} alerts</dd></div><div><dt className="text-xs uppercase text-muted-foreground">Coverage</dt><dd className="font-semibold">{audit.coverageContribution.length ? audit.coverageContribution.join(", ") : "Standard contribution"}</dd></div></dl>{audit.blocking.length || audit.warnings.length ? <ul className="space-y-1 text-sm">{[...audit.blocking, ...audit.warnings].slice(0, 6).map((finding, index) => <li key={`${finding.code}-${finding.path}-${index}`}><Badge variant={finding.severity === "blocking" ? "warning" : "subtle"}>{finding.code}</Badge> <span className="text-muted-foreground">{finding.message}</span></li>)}</ul> : null}{audit.similarity.length ? <ul className="space-y-1 text-sm">{audit.similarity.slice(0, 4).map((similarity) => <li key={`${similarity.packId}-${similarity.otherPackId}`}><strong>Possible overlap with {similarity.otherTitle}:</strong> {similarity.kinds.map(label).join(", ")} · source {Math.round(similarity.sourceSimilarity * 100)}% · questions {Math.round(similarity.questionSimilarity * 100)}%</li>)}</ul> : null}<Button asChild size="sm" variant="outline"><Link href={`/admin/general-academic/${audit.item.id}/review` as Route}>Open pack review</Link></Button></CardContent></Card>)}{!audits.length ? <p className="rounded-lg border border-workspace-border bg-surface-container p-4 text-sm">No packs match these filters.</p> : null}</section>

      <Card><CardHeader><CardTitle>Origin outcomes</CardTitle><CardDescription>Measurable inventory and deterministic findings by provenance. No subjective provider ranking is inferred.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr><th className="border-b p-2">Origin</th><th className="border-b p-2">Active packs</th><th className="border-b p-2">Questions</th><th className="border-b p-2">Published packs</th><th className="border-b p-2">Warnings</th><th className="border-b p-2">Similarity alerts</th></tr></thead><tbody>{GENERAL_ACADEMIC_ORIGINS.map((origin) => { const originAudits = health.audit.audits.filter((audit) => audit.item.pack.review.status !== "archived" && audit.item.pack.origin === origin); return <tr key={origin}><th className="border-b p-2" scope="row">{label(origin)}</th><td className="border-b p-2">{health.audit.coverage.origins[origin].packs}</td><td className="border-b p-2">{health.audit.coverage.origins[origin].questions}</td><td className="border-b p-2">{health.audit.coverage.origins[origin].publishedPacks}</td><td className="border-b p-2">{originAudits.reduce((sum, audit) => sum + audit.warnings.length, 0)}</td><td className="border-b p-2">{originAudits.reduce((sum, audit) => sum + audit.similarity.length, 0)}</td></tr>; })}</tbody></table></CardContent></Card>
    </div>
  );
}
